"""
About:This is the second stage of the MarketFed
automated pipeline.

Purpose: It checks for the fitness of the extracted CSV file
generated by extract.py before any transformation
or modelling starts.

There are two layers to this validation:
1.) Schema validation to check column names,
data types and missing values
2.)Business/Project Logic Validation to chack target markets and commodities,
sufficient date range, and no duplicate records

INPUT: wfp_nga_cereals_20260709_152155.csv

OUTPUT/DELIVERABLE: 
1. A valiadted DataFrame with all check passed
A data quality report with timestamped saved in .json

The report documents every check that ran, its result and 
summary of the statistics.

To Execute:
1.) python -m pipeline.validate (standalone)
2.) python -m pipeline.run (when run with prefect flow)
"""
import os
os.environ["DISABLE_PANDERA_IMPORT_WARNING"] = "True"

import pandera as pa
import pandas as pd
from pandera import Column, DataFrameSchema, Check
from prefect import task, get_run_logger

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from pipeline import extract

from pipeline.config import(
    TARGET_MARKETS,
    TARGET_COMMODITIES,
    TARGET_CATEGORY,
    QUALITY_DIR,
)

def _create_dir(path: Path) -> Path:
    """Create directory if it does not exist at path,
    and return the path.
    """
    path.mkdir(parents=True, exist_ok=True)
    return path

def _path_report_timestamped() -> Path:
    """This generates a unique time-stamped data quality report per execution
    it gives a complete audit trail of data quality over time"""
    
    time_stamped = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    file_name = f"data_quality_report_{time_stamped}.json"
    return _create_dir(QUALITY_DIR) / file_name 


def _build_schema() -> DataFrameSchema:
    """It builds and return the pandera validated DataFrameSchema for
    the extracted CSV data. It ensures data is successfully screened for
    modelling purpose"""

    return DataFrameSchema(
        columns={"date": Column(
            pa.String, nullable=False,description="Price observation date(YYYY-MM-DD)"
        ),

        "admin1": Column(
            pa.String, nullable=False, description="State name"
        ),
        "admin2": Column(
            pa.String, nullable=False,description="LGA or city name"
        ),
        "market": Column(
            pa.String, Check.isin(TARGET_MARKETS),
            nullable=False,
            description="Market name - must match TARGET_MARKETS"
        ),
        "market_id": Column(
            pa.Int, nullable=False,description="Numeric marekt identifier"
        ),
        "latitude": Column(
            pa.Float, Check.in_range(-90,90),nullable=False,description="Market GPS latitude"
        ),
        "longitude": Column(
            pa.Float, Check.in_range(-180, 180),nullable=False,description="Market GPS longitude"
        ),"category": Column(
            pa.String, Check.isin([TARGET_CATEGORY]),nullable=False,description="Food category"
        ),
        "commodity": Column(
            pa.String, Check.isin(TARGET_COMMODITIES),nullable=False,
            description="Commodity name: must match TARGET_COMMODITIES"
        ),
        "commodity_id": Column(
            pa.Int, nullable=False,description="Numeric commodity identifier"
        ),
        "unit": Column(
            pa.String, Check.isin(["100 KG", "50 KG", "KG", "2.6 KG", "2.8 KG"]), nullable=False,description="Unit of measurement per 100 kg"
        ),
        "priceflag": Column(
            pa.String, nullable=False,description="Data quality flag"
        ),
        "pricetype": Column(
            pa.String, Check.isin(["Wholesale", "Retail"]),nullable=False,description="Price type"
        ),
        "currency": Column(
            pa.String, Check.isin(["NGN"]),nullable=False,description="Currency in NGN for Nigeria"
        ),
        "price": Column(
            pa.Float, Check.greater_than(0),nullable=False,description="Price in NGN must be positive"
        ),
        "usdprice": Column(
            pa.Float, Check.greater_than(0),nullable=True,description="Comparable price in USD: nullable for historical gaps"

        ),

        },
    )

def _generate_data_quality_report(df: pd.DataFrame, schema_passed:bool, schema_errors: list) -> dict:
    """This function generates the data quality reports from the pandera
    validated DataFrame. he report is stored in a dictionary. The report has three sections:
    1. Summary of the dataframe (rows, and column counts, fail or pass status)
    2. A checklist of each business rule
    3. The statistics of the numerical variable columns"""

    present_markets = sorted(df["market"].unique().tolist())
    present_commodities = sorted(df["commodity"].unique().tolist())
    missing_markets = sorted(set(TARGET_MARKETS)-set(present_markets))
    missing_commodities = sorted(set(TARGET_COMMODITIES) - set(present_commodities))

    ## Range of Date ###
    df["date"] = pd.to_datetime(df["date"])
    date_min = df["date"].min()
    date_max = df["date"].max()
    date_range_years = (date_max - date_min).days / 365
    least_date_range = date_range_years >=5.0

    ### Detect Duplicates ##
    duplicate_data = df.duplicated(subset=["date", "market", "commodity"]).sum()

    null_rate = {col: round(df[col].isna().mean() * 100,2) for col in df.columns}

    ## Detect outliers in price ##
    price_stats = df["price"].describe()

    ## Measure the relative stability of the price ##
    price_coefficient_of_variation = (df["price"].std() / df["price"].mean()) * 100

    ## Create Report ###
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pipeline_stage": "validate.py",
        "summary": {
            "total_rows": len(df),
            "total_columns": len(df.columns),
            "schema_passed": schema_passed,
            "all_checks_passed": (
                schema_passed
                and len(missing_markets) == 0
                and len(missing_commodities) == 0
                and least_date_range
                #and duplicate_data == 0
            ),
        },
        "schema_validation": {
            "passed": schema_passed,
            "errors": schema_errors,
        },
        "business_rule_checks": {
            "markets_expected": TARGET_MARKETS,
            "present_markets": present_markets,
            "missing_markets": missing_markets,
            "markets_check": len(missing_markets) == 0,
            "commodities_expected": TARGET_COMMODITIES,
            "present_commodities": present_commodities,
            "missing_commodities": missing_commodities,
            "commodities_check": len(missing_commodities) == 0,
            "date_range_earliest": date_min.isoformat(),
            "date_range_latest": date_max.isoformat(),
            "date_range_years": round(date_range_years, 1),
            "date_range_check": least_date_range,
            "duplicate_records": int(duplicate_data),
            "duplicate_check": duplicate_data == 0,

        },
        "null_rates_percent": null_rate,
        "price_statistics": {
            "min": round(price_stats["min"], 2),
            "max": round(price_stats["max"], 2),
            "mean": round(price_stats["mean"], 2),
            "median": round(price_stats["50%"], 2),
            "std": round(price_stats["std"], 2),
            "coefficient_of_variation_pcts": round(price_coefficient_of_variation, 1),

        },
    }

    return report

## The data validation function that returns the validated data frame##
raw_path = extract.extract_data()
#data_frame =   #validate_data(raw_path)
#data_frame_clean =   transform_data(raw_path) #transform_data(data_frame)

@task(
    name = "validate-wfp-nigeria",
    retries = 3,
    retry_delay_seconds = 15,
    description = (
        "Validates the messy WFP Nigeria CSV data for maize, rice and millet."
        "Run pandera schema and check out the business logic successfully."
        "Save JSON quality report to data/quality_reports/."
    ),
)
def validate_data(raw_path: Path) -> pd.DataFrame:
    """
    The main data validation function that serves as the public entry point 
    for the validate.py module or file. It takes the path to the CSV file
    produced in extract.py module and validates it before returning it as 
    a pandas data-frame to used by the transform.py module. 
    """
    try:
        logger = get_run_logger()
    except Exception:
        logger = logging.getLogger("src.pipeline.validate")
    logger.info("== Data Loading started==")
    logger.info(f"Input file: {raw_path}")

    ## Stage 1: Load the extracted CSV file ##
    data_frame = pd.read_csv(raw_path)
    logger.info(
        f"Loaded {len(data_frame):,} rows"
        f"{len(data_frame.columns)} columns"
    )

    ## Stage 2: Pandera schema validation ##
    schema = _build_schema()
    schema_passed = True
    schema_errors = []

    try:
        schema.validate(data_frame, lazy=True)
        logger.info("Schema validation: Passed")

    except pa.errors.SchemaErrors as exc:
        schema_passed = False
        schema_errors = (
            exc.failure_cases["failure_case"]
            .astype(str)
            .unique()
            .tolist()
        )
        logger.warning(
            f"Schema validation: FAILED - "
            f"{len(schema_errors)} issue(s) found"
        )
        for an_error in schema_errors[:5]:
            logger.warning(f" -> {an_error}")
    
    ## Build the data quality report ##
    report = _generate_data_quality_report(data_frame,schema_passed,schema_errors)
    all_passed = report["summary"]["all_checks_passed"]

    ## Save the qualtiy report to disk ##
    report_path = _path_report_timestamped()
    with open(report_path, "w", encoding="utf-8") as data_file:
        json.dump(report, data_file, indent=2, default=str)
    logger.info(f"Quality report saved -> {report_path.name}")

    ## Log the report summary ##
    logger.info("===Summary of validation===")
    logger.info(
        f" Rows checked : {report['summary']['total_rows']:,}"
    )
    logger.info(
        f" Schema passed : {schema_passed}"
    )
    logger.info(
        f" Markets present :"
        f"{report['business_rule_checks']['present_markets']}"
    )
    logger.info(
        f" Date range :"
        f"{report['business_rule_checks']['duplicate_records']}"
    )
    logger.info(
        f" Duplicates found: "
        f"{report['business_rule_checks']['date_range_years']}"
    )
    logger.info(f" All checks passed: {all_passed}")

    checks = report["business_rule_checks"]

    if not checks["markets_check"]:
        raise ValueError(
            f"Critical: missing markets in data - "
            f"{checks['missing_markets']}. "
            f"Check TARGET_MARKETS in config.py."
        )
    if not checks["commodities_check"]:
        raise ValueError(
            f"Critical: missing commodities in data - "
            f"{checks['commodities_missing']}. "
            f"Check TARGET_COMMODITIES in config.py."
        )
    if not checks["date_range_check"]:
        raise ValueError(
            f"Critical: date range too sort -"
            f"{checks['date_range_years']} years."
            f"Need at least 5 years of data for forecasting."
        )
    logger.info("=== Completed data validation ===")

    if not checks["duplicate_check"]:
        logger.warning(
        f"Warning: {checks['duplicate_records']} duplicate "
        f"records found. These will be handled in transform.py."
    )

    return data_frame

## Enable testing validate.py directly from the terminal with Standalone Runner below ##
if __name__ == "__main__":
    import sys

    logging.basicConfig(
        level = logging.INFO,
        format = "%(asctime)s | %(levelname)s | %(message)s",
        datefmt = "%Y-%m-%d %H:%M:%S",
    )
    log = logging.getLogger(__name__)

    ## This locates the most recent raw file automatically ##
    raw_files = sorted(Path("data/raw").glob("*.csv"))

    if not raw_files:
        log.error(
            "No raw CSV files found in data/raw/."
            "Execute extract.py file first."
        )
        sys.exit(1)
    latest_file = raw_files[-1]
    log.info(f"Validating recent files: {latest_file.name}")

    validated_data_frame = validate_data.fn(latest_file) ## validation check ##
    report_files = sorted(Path("data/quality_reports").glob("*.json"))
     
    if report_files:
        latest_report = report_files[-1]
        with open(latest_report, encoding="utf-8") as a_report:
            report = json.load(a_report)
        print("\n" + "=" * 30)
        print("QUALITY REPORT SUMMARY")
        print("=" * 30)
        print(
            f"Generated : {report['generated_at']}"
        )
        print(
            f"Total rows :"
            f"{report['summary']['total_rows']:,}"
        )
        print(
            f"Schema passed: "
            f"{report['schema_validation']['passed']}"
        )
        print(
            f"All passed : "
            f"{report['summary']['all_checks_passed']}"
        )
        print()
        print("Business Rule Checks:")
        checks = report["business_rule_checks"]
        print(
            f" Markets :"
            f"{'PASS' if checks['markets_check'] else 'FAIL'}"
            f"-> {checks['present_markets']}"
        )
        print(
            f" Commodities :"
            f"{'PASS'if checks['commodities_check'] else 'FAIL'}"
            f"-> {checks['present_commodities']} years"
        )
        print(
            f" Date range : "
            f"{'PASS' if checks['date_range_check'] else 'FAIL'}"
            f"-> {checks['date_range_years']} years"
        )
        print(
            f" Duplicates : "
            f"{'PASS' if checks['duplicate_check'] else 'FAIL'}"
            f"-> {checks['duplicate_records']} found"
        )
        print()
        print(" Null Rates (%)")
        for col, rate in report["null_rates_percent"].items():
            flag = " " if rate > 5 else ""
            print(f" {col:<20} {rate}{flag}")
        print()
        
        print("Price Statistics (NGN):")
        stats = report["price_statistics"]
        print(f"  Min    : {stats['min']:,.2f}")
        print(f"  Max    : {stats['max']:,.2f}")
        print(f"  Mean   : {stats['mean']:,.2f}")
        print(f"  Median : {stats['median']:,.2f}")
        print(f"  CV%    : {stats['coefficient_of_variation_pcts']}")
        print("=" * 55)
        print(f"Full report : {latest_report}")
        print("=" * 55)
        

